### PR TITLE
Use ChaincodeStubInterface

### PR DESCRIPTION
**Pull request by brad-gorman**
For whenever the changes get made to hyperledger/fabric to stop using *shim.ChaincodeStub and use an interface instead.

Signed-off-by: Bradley Gorman <bgorman@au1.ibm.com>

### CODE REVIEW

**Comment by brad-gorman** [comment]
Signed-off-by: Bradley Gorman <bgorman@au1.ibm.com>

**Comment by ghaskins** [comment]
Thanks @brad-gorman.  Changes LGTM.  I'll coordinate the merge with fabric status.

**Comment by ghaskins** [comment]
Now that the fabric patch has merged, we will look at getting this merged asap.

**Comment by ghaskins** [comment]
LGTM

**Pull request merged**
